src/Entity/Ticket.php
<?php

namespace App\Entity;

use App\Repository\TicketRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TicketRepository::class)
 */
class Ticket
{
    const MEDIUM_PRIORITY = 5;
    const MIN_PRIORITY = 0;
    const MAX_PRIORITY = 10;
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="ticket")
     */
    private $created_by;

    /**
     * @ORM\Column(type="string", length=1000)
     */
    private $message;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $status;

    /**
     * @ORM\Column(type="datetime")
     */
    private $creation_time;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="ticket")
     */
    private $handling_agent;

    /**
     * @ORM\OneToMany(targetEntity=CommentHistory::class, mappedBy="ticket_id", orphanRemoval=true)
     */
    private $commentHistories;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_escalated;

    /**
     * @ORM\Column(type="integer")
     */
    private $times_reopened;

    /**
     * @ORM\Column(type="integer")
     */
    private $priorities;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_message_time;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    public function __construct()
    {
        $this->commentHistories = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreatedBy(): ?User
    {
        return $this->created_by;
    }

    public function setCreatedBy(User $user): void
    {
        $this->created_by = $user;

        //return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): void
    {
        $this->message = $message;

        //return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): void
    {
        $this->status = $status;

        //return $this;
    }

    public function getCreationTime(): ?\DateTimeInterface
    {
        return $this->creation_time;
    }

    public function setCreationTime(\DateTimeInterface $creation_time): void
    {
        $this->creation_time = $creation_time;

        //return $this;
    }

    public function getHandlingAgent(): ?User
    {
        return $this->handling_agent;
    }

    public function setHandlingAgent(?User $handling_agent): void
    {
        $this->handling_agent = $handling_agent;

        //return $this;
    }

    /**
     * @return Collection|CommentHistory[]
     */
    public function getCommentHistories(): Collection
    {
        return $this->commentHistories;
    }

    public function addCommentHistory(CommentHistory $commentHistory): self
    {
        if (!$this->commentHistories->contains($commentHistory)) {
            $this->commentHistories[] = $commentHistory;
            $commentHistory->setTicket($this);
        }

        return $this;
    }

    public function removeCommentHistory(CommentHistory $commentHistory): self
    {
        if ($this->commentHistories->contains($commentHistory)) {
            $this->commentHistories->removeElement($commentHistory);
            // set the owning side to null (unless already changed)
            if ($commentHistory->getTicket() === $this) {
                $commentHistory->setTicket(null);
            }
        }

        return $this;
    }

    public function getIsEscalated(): ?bool
    {
        return $this->is_escalated;
    }

    public function setIsEscalated(bool $is_escalated): void
    {
        $this->is_escalated = $is_escalated;

        //return $this;
    }

    public function getTimesReopened(): ?int
    {
        return $this->times_reopened;
    }

    public function setTimesReopened(int $times_reopened): void
    {
        $this->times_reopened = $times_reopened;

        //return $this;
    }

    public function getPriorities(): ?int
    {
        return $this->priorities;
    }

    public function setPriorities(int $priorities): void
    {
        $this->priorities = $priorities;

        //return $this;
    }

    public function getUpdatedMessageTime(): ?\DateTimeInterface
    {
        return $this->updated_message_time;
    }

    public function setUpdatedMessageTime(?\DateTimeInterface $updated_message_time): void
    {
        $this->updated_message_time = $updated_message_time;

        //return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): void
    {
        $this->title = $title;

        //return $this;
    }

    public function setDefaults(): void
    {
        $this->status = 'open';
        $this->is_escalated = false;
        $this->times_reopened = 0;
        $this->priorities = self::MEDIUM_PRIORITY;
        $this->creation_time = new \DateTimeImmutable();
    }
}

src/Controller/CustomerController.php
<?php

namespace App\Controller;

use App\Entity\CommentHistory;
use App\Entity\Ticket;
use App\Entity\User;
use App\Form\NewTicketType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class CustomerController extends AbstractController
{
    /**
     * @Route("/customer", name="customer")
     */
    public function index(): Response
    {
        $defaultmessage = "You have no open tickets!";
        $repository = $this->getDoctrine()->getRepository(Ticket::class);
        $userId = 1;
        $tickets = $repository->findBy(
            ['created_by' => $userId],
            ['id' => 'ASC']
        );


        return $this->render('customer/index.html.twig', [
            'tickets' => $tickets,
            'message' => $defaultmessage
        ]);
    }

    /**
     * @Route("/customer/ticket/{id}", name="customer-ticket-details", methods={"GET", "POST"})
     * @param Ticket $ticket
     * @param Request $request
     * @return Response
     */
    public function ticketDetail(Ticket $ticket, Request $request): Response
    {
        $repository = $this->getDoctrine()->getRepository(User::class);
        $user = $repository->find($ticket->getCreatedBy());
        $displayCommentField = false;
        $status = $ticket->getStatus();
        //$data = $request->get("save_comment");

        if ($request->get("add_comment")) {
            $displayCommentField = true;
        }

        if($request->get('reopen') && $status === 'Closed'){
            $ticket->setStatus('open');
            $ticket->setUpdatedMessageTime(new \DateTimeImmutable());
        }
        if(!empty($request->get('comment'))){
            $manager = $this->getDoctrine()->getManager();
            $ticket->setUpdatedMessageTime(new \DateTimeImmutable());
            $newComment = new CommentHistory();
            $newComment
                ->setCreatedBy($user)
                ->setComments($request->get('comment'))
                ->setTicket($ticket)
                ->setIsPrivate(false) //set defaults in constructor
                ->setFromManager(false);
            $manager->persist($newComment);
            $manager->persist($ticket);
            $manager->flush();
        }
        $comments = $this->getDoctrine()->getRepository(CommentHistory::class)->findBy(
            ['ticket' => $ticket->getId()],
            ['id' => 'DESC']
        );

        $this->getDoctrine()->getManager()->persist($ticket);
        $this->getDoctrine()->getManager()->flush();

        $lastResponse = $ticket->getUpdatedMessageTime();
        $status = $ticket->getStatus();
        return $this->render('customer/ticket_detail.html.twig', [
            'ticket' => $ticket,
            'user' => $user,
            'displayfield' => $displayCommentField,
            'comments' => $comments,
            'lastResponse' => $lastResponse,
            'status' => $status

        ]);
    }

    /**
     * @Route("/customer/new_ticket", name="new_ticket", methods={"GET", "POST"})
     * @param Request $request
     * @return Response
     */
    public function newTicket(Request $request): Response
    {
        $message = "Create a ticket here";

        $user = $this->getDoctrine()->getRepository(User::class)->find(1);


        if ($request->get('new_ticket')) {
            $data = $request->request->get('new_ticket');
            //$createdBy = $data['created_by'];
            $title = $data['title'];
            $content = $data['message'];
            //$user_id = 1; // change to session user_id

            $ticket = new Ticket();
            $ticket->setDefaults();
            $ticket->setTitle($title);
            $ticket->setMessage($content);
            $ticket->setCreatedBy($user);

            $message = 'Ticket created';

            $manager = $this->getDoctrine()->getManager();
            $manager->persist($ticket);
            $manager->flush();
        }


        $ticket = new Ticket();
        $form = $this->createForm(NewTicketType::class, $ticket);
        return $this->render('user/new_ticket.html.twig', [
            'new_ticket_form' => $form->createView(),
            'message' => $message

        ]);
    }
}

templates/customer/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello CustomerController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello! ✅</h1>
    <a href="{{ path('new_ticket') }}">Create new issue</a>



    <h2>Your tickets: </h2>

    <ul>
        {% for ticket in tickets %}
        <li>Created: {{ ticket.creationTime|date("m/d/Y") }} <a href="{{ path('customer-ticket-details', {id: ticket.id}) }}" title="Show details">{{ ticket.title }}</a></li>

            {% else %}
            <p>{{ message }}</p>
        {% endfor %}
    </ul>
</div>
{% endblock %}

templates/customer/ticket_detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello CustomerController!{% endblock %}

{% block body %}
    <style>
        .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
        .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
    </style>

    <div class="example-wrapper">
        <a href="{{ path('customer') }}">Back to Homepage</a>
            <h5>Created: {{ ticket.creationTime|date() }}</h5>
            <h2>Title: {{ ticket.title }}</h2>
            <p>{{ ticket.message }}</p>
        <p><i>Created by {{ user.email }}</i></p>
        {#<form action="{{ path('customer-ticket-details', {id: ticket.id}) }}"></form>#}
        {% if not displayfield %}
            <form action="#">
                <input type="submit" value="Add new comment" name="add_comment" method="POST">
            </form>
        {% else %}
            <form action="#">
                <textarea placeholder="Write down your question or issue here and we'll get back to you as soon as there is a new Belgian government" name="comment"></textarea>
                <input type="submit" value="Add new comment" name="save_comment" method="POST">
            </form>
        {% endif %}
        {#{% if message %}

        {% endif %}#}
        <br>
        <div>

            {% if status == 'Closed' %}
                Your ticket has been closed. <br>
                <form action="#" method="post">
                    <input type="submit" value="Reopen ticket" name="reopen">
                </form>
            {% endif %}
            <h3>Reactions: {% if lastResponse %}(last reaction: {{ lastResponse|date() }}){% endif %}</h3><br>
            {% for comment in comments %}
            <p>{{ comment.comments }}</p>
            {% else %}
            <p>No reactions to be shown.</p>
            {% endfor %}
        </div>
    </div>
{% endblock %}